# Generated by Django 5.1.1 on 2024-10-06 16:56

import forumApp.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[forumApp.posts.validators.UniquePostTitleValidator()]),
        ),
    ]
