# Generated by Django 5.1.1 on 2024-10-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_like_to_photo_photocomment_photolike_and_more'),
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='PhotoLike',
            new_name='Like',
        ),
    ]
